### PR TITLE
add channelized frequency and signal level to acars output

### PR DESCRIPTION
**Pull request by rpatel3001**
for use with https://github.com/rpatel3001/docker-gr-iridium-toolkit and https://github.com/sdr-enthusiasts/docker-acarshub

### CODE REVIEW

**Comment by Sec42** [comment]
Can you provide some more reason/rationale for this? The channelize is a "guess" - it will be off by +/- 1 channel due to doppler shift, so I don't think it is very useful to propagate that to users.

**Comment by rpatel3001** [comment]
I just like having the data in my acarshub stats and I think others will too.

Also, I think having a +/- 1 channel frequency guess is better than not having any frequency data.

**Comment by rpatel3001** [comment]
That would be fine, we can channelize externally (to limit how long the frequency list in acarshub gets)

**Comment by rpatel3001** [comment]
good to merge?

**Pull request merged**
