### PR TITLE
ACARS JSON to airframes.io 

### PR DESCRIPTION
**Pull request by kevinelliott**
This builds on previous work I did to add JSON output to the ACARS parser. It augments the output to be in the format that Airframes is expecting, and also adds a script that can be piped to in order to send the output. The sender script also supports having additional remote outputs.

Example usage:
```bash
$ export PYTHONUNBUFFERED=x; ./reassembler.py -i zmq: -m acars -a json --station YOUR_STATION_IDENT | ./iridium-acars-to-airframes.py
```

In order to send to additional outputs, simply add `-o tcp:hostname:port` as many times to the `iridium-acars-to-airframes.py` command.

### CODE REVIEW

**Comment by Sec42** [comment]
Thanks for the code. The fact that you have a station override bit in the airframes script makes me think about weather the specific json structure field mapping should maybe be moved over there. Let me know if you have an argument either way, otherwise i'll think about it for a bit.

**Comment by kevinelliott** [comment]
> Thanks for the code. The fact that you have a station override bit in the airframes script makes me think about weather the specific json structure field mapping should maybe be moved over there. Let me know if you have an argument either way, otherwise i'll think about it for a bit.

I don't have a compelling argument either way. It was originally put there just in case someone wanted to run multiple instances and have different station ids, but ultimately I think that isn't very beneficial (as it would really just end up sending the same data for multiple station ids for no reason).

**Comment by Sec42** [comment]
Turns out I currently don't have the energy to do any changes. Sorry for the delay. Is this still the current version to be merged?

**Comment by kevinelliott** [comment]
@Sec42 merge away!

**Comment by Sec42** [comment]
merged

**Comment by alphafox02** [comment]
@Sec42 was this merged ever or just closed? Someone messaged me about the json format and that it no longer works - which lead me back here to this page. I think in previous builds I must have used the fork and then thought it was merged into the main project and switched back.

**Pull request closed without merging**
