### PR TITLE
Acars feed updates

### PR DESCRIPTION
**Pull request by murrayma**
Fixes for socket reconnection in the python script used to feed ACARS messages to airframes.io. These changes have been reviewed by @kevinelliott so I believe he will support this PR.

### CODE REVIEW

**Comment by kevinelliott** [comment]
This is great. Several users have confirmed that this fixes the disconnection/reconnection issues. Thank you @murrayma for taking this on and submitting the fix.

@Sec42 this is ready for merge.

**Comment by kevinelliott** [comment]
Sorry to have left this hanging. This is blessed! Thanks @murrayma ... please merge @Sec42

**Comment by kevinelliott** [comment]
@murrayma @Sec42 Ping!

**Comment by kevinelliott** [comment]
Hi @Sec42 -- I'm sure you're busy over there. Just a reminder again. I know that a few people are looking forward to this. Thank you!

**Review by kevinelliott — APPROVED** [review]

**Comment by Sec42** [comment]
Hey. For whatever reason I didn't get your other messages. I think they got eaten by the spam filter. Anyway. Will get to it latest this weekend. Sorry.

**Comment by Sec42** [comment]
merged. Hope it works for you.

**Pull request merged**
